#!/usr/bin/env bash
################################################################################
# Author: @gubatron - September 2019
# Modified: 2025 - Refactored for Windows build (cross-compile from Linux)
# This script builds fwplayer.exe for Windows x86_64
# functions are defined in build-functions.sh
# ffmpeg codec flag related variables are generated by prepare_ffmpeg_flags.sh
# as output strings which are evaluated by prepare_ffmpeg_flags
################################################################################
#set -x

if [ -z "${OPENSSL_ROOT}" ]; then
    set +x
    clear
    echo "OPENSSL_ROOT not set."
    echo
    echo "   It should point to an openssl installation folder (not the sources)"
    echo
    echo "   For Windows cross-compilation from Linux:"
    echo "   export OPENSSL_ROOT=${HOME}/src/openssl-win64-x86_64"
    echo
    exit 1
fi

export PKG_CONFIG_PATH="${OPENSSL_ROOT}/lib/pkgconfig"
source build-functions.sh

# Verify we're on Linux for cross-compilation
if ! is_linux; then
    echo "Error: Windows builds must be done from Linux (cross-compilation)"
    exit 1
fi

ARCH="x86_64"
echo "Building fwplayer.exe for Windows (${ARCH}) from Linux"
press_any_key

prepare_enabled_protocol_flags
if [ -z "${ENABLED_PROTOCOLS_FLAGS}" ]; then
  echo "Error: ENABLED_PROTOCOLS_FLAGS is unset"
  echo ${ENABLED_PROTOCOLS_FLAGS}
  exit 1
fi

verify_mplayer_source || exit 1
verify_ffmpeg_source || exit 1

prepare_ffmpeg_flags
verify_ffmpeg_flags || exit 1

# First we need to build ffmpeg
configure_ffmpeg_windows
make -j 8

# Remove problematic codec object files that cause linking errors
# These have unresolved dependencies when built for audio-only player
cleanup_ffmpeg_problematic_objects

# Pop back to mplayer-trunk directory (we were in ffmpeg for cleanup)
popd

# Ensure we're in mplayer-trunk directory
ensure_cd "mplayer-trunk" || exit 1

echo "FFMpeg compilation finished"
press_any_key

################################################################################
# Configure MPlayer Build for Windows
################################################################################

CC="x86_64-w64-mingw32-gcc"
WINDRES="x86_64-w64-mingw32-windres"
WARNING_FLAGS='-Wno-error=implicit-function-declaration -Wno-unused-function -Wno-switch -Wno-expansion-to-defined -Wno-deprecated-declarations -Wno-shift-negative-value -Wno-pointer-sign -Wno-parentheses -Wdangling-else'
CONFIG_OPTS="--enable-static --windres=${WINDRES} --disable-pthreads --target=x86_64-mingw32 --enable-cross-compile --cc=${CC} --enable-winsock2_h"
EXTRA_LDFLAGS="-L${OPENSSL_ROOT}/lib -lssl -lcrypto -Lffmpeg/libavutil -lavutil"
EXTRA_CFLAGS="${WARNING_FLAGS} -mtune=generic -fPIC -Os -I/usr/x86_64-w64-mingw32/include -I${OPENSSL_ROOT}/include"

./configure \
${CONFIG_OPTS} \
--enable-openssl-nondistributable \
--disable-gnutls \
--disable-iconv \
--disable-mencoder \
--disable-vidix \
--disable-vidix-pcidb \
--disable-matrixview \
--disable-xss \
--disable-tga \
--disable-pnm \
--disable-md5sum \
--disable-yuv4mpeg \
--disable-png \
--disable-quartz \
--disable-vcd \
--disable-bluray \
--disable-dvdnav \
--disable-dvdread \
--disable-alsa \
--disable-ossaudio \
--disable-arts \
--disable-esd \
--disable-pulse \
--disable-jack \
--disable-openal \
--disable-nas \
--disable-sgiaudio \
--disable-sunaudio \
--disable-kai \
--disable-dart \
--disable-win32waveout \
--disable-select \
--disable-win32dll \
--disable-gl \
--disable-matrixview \
--disable-vesa \
--disable-sdl \
--disable-aa \
--disable-caca \
--disable-ggi \
--disable-ggiwmh \
--disable-direct3d \
--disable-directx \
--disable-dxr2 \
--disable-dxr3 \
--disable-v4l2 \
--disable-dvb \
--disable-mga \
--disable-xmga \
--disable-xv \
--disable-vda \
--disable-vdpau \
--disable-vm \
--disable-xinerama \
--disable-x11 \
--disable-xshape \
--disable-fbdev \
--disable-mlib \
--disable-3dfx \
--disable-tdfxfb \
--disable-s3fb \
--disable-wii \
--disable-directfb \
--disable-zr \
--disable-bl \
--disable-tdfxvid \
--disable-xvr100 \
--extra-cflags="${EXTRA_CFLAGS}" \
--extra-ldflags="${EXTRA_LDFLAGS}"

press_any_key
make -j 8

strip_and_upx_final_executable "windows" "x86_64"

popd
pwd
set +x
