#!/usr/bin/env bash
################################################################################
# Author: @gubatron - September 2019
# Modified: 2025 - Refactored for Windows build (cross-compile from Linux)
# This script builds fwplayer.exe for Windows x86_64
# Audio-only player (no video support)
# We build everything with a single configure from MPlayer and it will
# subsequently build ffmpeg for us
# functions are defined in build-functions.sh
################################################################################
#set -x

source build-functions.sh

# Verify we're on x86_64 architecture
# (Ubuntu Linux is verified by Docker or the calling script)
if [ "$(uname -m)" != "x86_64" ]; then
    echo "Error: Windows cross-compilation requires x86_64 architecture"
    exit 1
fi

ARCH="x86_64"
echo "Building fwplayer.exe for Windows (${ARCH}) from Linux"
press_any_key

cd MPlayer-1.5

# Clean both MPlayer and FFmpeg
ALLCODECS_BACKUP="$(mktemp)"
if [ -f ffmpeg/libavcodec/allcodecs.c ]; then
    cp ffmpeg/libavcodec/allcodecs.c "${ALLCODECS_BACKUP}"
else
    ALLCODECS_BACKUP=""
fi

make clean
make -C ffmpeg clean

if [ ! -f ffmpeg/libavcodec/allcodecs.c ]; then
    if [ -n "${ALLCODECS_BACKUP}" ]; then
        cp "${ALLCODECS_BACKUP}" ffmpeg/libavcodec/allcodecs.c
    else
        echo "Restoring ffmpeg/libavcodec/allcodecs.c from Git HEAD"
        git -C .. show HEAD:MPlayer-1.5/ffmpeg/libavcodec/allcodecs.c > ffmpeg/libavcodec/allcodecs.c
    fi
fi
[ -n "${ALLCODECS_BACKUP}" ] && rm -f "${ALLCODECS_BACKUP}"

if [ ! -f ../enabled-decoders.txt ]; then
    echo "Error: ../enabled-decoders.txt not found"
    exit 1
fi

CC="x86_64-w64-mingw32-gcc"
WINDRES="x86_64-w64-mingw32-windres"
WARNING_FLAGS='-Wno-error=implicit-function-declaration -Wno-unused-function -Wno-switch -Wno-expansion-to-defined -Wno-deprecated-declarations -Wno-shift-negative-value -Wno-pointer-sign -Wno-parentheses -Wdangling-else'
EXTRA_LDFLAGS=""

ENABLED_DECODERS=()
DECODER_HEADER_PATH="${PWD}/audio_decoder_overrides.h"

while read -r decoder; do
    [ -z "${decoder}" ] && continue
    ENABLED_DECODERS+=("${decoder}")
done < <(tr '[:space:]' '\n' < ../enabled-decoders.txt | sed '/^$/d')

generate_decoder_overrides_header() {
    local header="${DECODER_HEADER_PATH}"
    local tmp_all
    tmp_all=$(mktemp /tmp/audio-macros.XXXXXX)

    {
        grep -Rho 'CONFIG_[A-Z0-9_]*_DECODER' ffmpeg 2>/dev/null || true
        grep -Rho 'CONFIG_[A-Z0-9_]*_ENCODER' ffmpeg 2>/dev/null || true
    } | sort -u > "${tmp_all}"

    {
        echo "/*"
        echo " * Auto-generated by build_windows.sh to keep FFmpeg locked to audio-only decoders."
        echo " * The file is regenerated on every run; do not edit manually."
        echo " */"
        echo "#pragma once"
        echo ""
        while read -r macro; do
            [ -z "${macro}" ] && continue
            echo "#undef ${macro}"
            echo "#define ${macro} 0"
        done < "${tmp_all}"
        for decoder in "${ENABLED_DECODERS[@]}"; do
            local macro_name="CONFIG_$(echo "${decoder}" | tr '[:lower:]' '[:upper:]')_DECODER"
            if grep -R "${macro_name}" ffmpeg >/dev/null 2>&1; then
                echo "#undef ${macro_name}"
                echo "#define ${macro_name} 1"
            else
                echo "/* Skipping unknown decoder macro ${macro_name} */"
            fi
        done
    } > "${header}"

    rm -f "${tmp_all}"
}

generate_decoder_overrides_header

has_decoder_symbol() {
    local symbol="$1"
    if command -v rg >/dev/null 2>&1; then
        rg -q --fixed-strings "const AVCodec ${symbol}" ffmpeg/libavcodec
    else
        grep -Rqs --fixed-strings "const AVCodec ${symbol}" ffmpeg/libavcodec
    fi
}

generate_codec_list() {
    local target="ffmpeg/libavcodec/codec_list.c"
    {
        echo "static const AVCodec *codec_list[] = {"
        for decoder in "${ENABLED_DECODERS[@]}"; do
            local lower="${decoder}"
            local symbol="ff_${lower}_decoder"
            if has_decoder_symbol "${symbol}"; then
                echo "    &${symbol},"
                continue
            fi
            if has_decoder_symbol "ff_${lower}_fixed_decoder"; then
                echo "    &ff_${lower}_fixed_decoder,"
                continue
            fi
            if has_decoder_symbol "ff_${lower}_float_decoder"; then
                echo "    &ff_${lower}_float_decoder,"
                continue
            fi
            echo "    /* Skipping unknown decoder symbol for ${decoder} */"
        done
        echo "    NULL };"
    } > "${target}"
}

DECODER_FLAGS=()
for decoder in "${ENABLED_DECODERS[@]}"; do
    DECODER_FLAGS+=("--enable-decoder=${decoder}")
done

EXTRA_CFLAGS="${WARNING_FLAGS} -mtune=generic -fPIC -Os -I/usr/x86_64-w64-mingw32/include -include ${DECODER_HEADER_PATH}"

DISABLED_COMPONENT_FLAGS=(
    --disable-gui
    --disable-gnutls
    --disable-librtmp
    --disable-iconv
    --disable-vidix
    --disable-vidix-pcidb
    --disable-matrixview
    --disable-xss
    --disable-tga
    --disable-pnm
    --disable-md5sum
    --disable-yuv4mpeg
    --disable-png
    --disable-vcd
    --disable-bluray
    --disable-dvdnav
    --disable-dvdread
    --disable-alsa
    --disable-ossaudio
    --disable-arts
    --disable-esd
    --disable-pulse
    --disable-jack
    --disable-openal
    --disable-nas
    --disable-sgiaudio
    --disable-sunaudio
    --disable-kai
    --disable-dart
    --disable-gl
    --disable-sdl
    --disable-aa
    --disable-caca
    --disable-ggi
    --disable-ggiwmh
    --disable-direct3d
    --disable-directx
    --disable-dxr2
    --disable-dxr3
    --disable-tv
    --disable-tv-v4l1
    --disable-tv-v4l2
    --disable-tv-bsdbt848
    --disable-v4l2
    --disable-dvb
    --disable-mga
    --disable-xmga
    --disable-xv
    --disable-vda
    --disable-vdpau
    --disable-vm
    --disable-xinerama
    --disable-x11
    --disable-xshape
    --disable-fbdev
    --disable-mlib
    --disable-3dfx
    --disable-tdfxfb
    --disable-s3fb
    --disable-wii
    --disable-directfb
    --disable-zr
    --disable-bl
    --disable-tdfxvid
    --disable-xvr100
    --disable-joystick
    --disable-radio
    --disable-live
    --disable-postproc
    --disable-runtime-cpudetection
    --disable-mencoder
)

CONFIGURE_FLAGS=(
    --target=x86_64-mingw32
    --enable-cross-compile
    --cc=${CC}
    --windres=${WINDRES}
    --enable-static
    --disable-pthreads
    --disable-decoder=all
    --disable-encoder=all
    --extra-cflags="${EXTRA_CFLAGS}"
    --extra-ldflags="${EXTRA_LDFLAGS}"
)

CONFIGURE_FLAGS+=("${DISABLED_COMPONENT_FLAGS[@]}")
CONFIGURE_FLAGS+=("${DECODER_FLAGS[@]}")

################################################################################
# Configure MPlayer Build for Windows (with integrated FFmpeg configuration)
################################################################################

echo "Running ./configure with audio-only flags:"
printf '  %s\n' "${CONFIGURE_FLAGS[@]}"

# We now build everything with a single configure from MPlayer and it will subsequently build ffmpeg for us
./configure "${CONFIGURE_FLAGS[@]}"

generate_codec_list

echo "Enforcing DirectSound + WaveOut audio outputs and stripping video leftovers"
if [ -f config.mak ]; then
    sed -i 's/^DIRECT3D = yes/DIRECT3D = no/' config.mak
    sed -i 's/^DIRECTX = yes/DIRECTX = no/' config.mak
    sed -i 's/^TGA = yes/TGA = no/' config.mak
    sed -i 's/^PNM = yes/PNM = no/' config.mak
    sed -i 's/^MD5SUM = yes/MD5SUM = no/' config.mak
    sed -i 's/^YUV4MPEG = yes/YUV4MPEG = no/' config.mak
    sed -i 's/^TV = yes/TV = no/' config.mak
    sed -i 's/^TV_DSHOW = yes/TV_DSHOW = no/' config.mak
fi
if [ -f config.h ]; then
    sed -i 's/#define CONFIG_DIRECT3D 1/#define CONFIG_DIRECT3D 0/' config.h
    sed -i 's/#define CONFIG_DIRECTX 1/#define CONFIG_DIRECTX 0/' config.h
fi

echo "Done with ./configure, next we build @ $(pwd)"
press_any_key

make -j 16

echo "Done building, now we'll rename mplayer to its new form for FrostWire @ $(pwd)"
strip_and_upx_final_executable "windows" "x86_64"
set +x
