#!/usr/bin/env bash
################################################################################
# Author: @gubatron
# Modified: 2025 - Refactored for native Linux builds
# This script builds a native fwplayer_linux binary for the host Linux architecture
# functions are defined in build-functions.sh
# ffmpeg codec flag related variables are generated by prepare_ffmpeg_flags.sh
# as output strings which are evaluated by prepare_ffmpeg_flags
################################################################################
#set -x

if [ -z "${OPENSSL_ROOT}" ]; then
    set +x
    clear
    echo "OPENSSL_ROOT not set."
    echo
    echo "   It should point to an openssl installation folder (not the sources)"
    echo
    echo "   For Linux native builds:"
    echo "   export OPENSSL_ROOT=${HOME}/src/openssl"
    echo
    exit 1
fi

export PKG_CONFIG_PATH="${OPENSSL_ROOT}/lib/pkgconfig"
source build-functions.sh

# Verify we're on Linux
if ! is_linux; then
    echo "Error: Linux builds must be done on Linux"
    exit 1
fi

ARCH=`arch`
if [ ${ARCH} == "i386" ]; then
    ARCH=x86_64
fi

if [ ${ARCH} == "aarch64" ]; then
    ARCH=arm64
fi

echo "Building native Linux player for architecture: ${ARCH}"
press_any_key

prepare_enabled_protocol_flags
if [ -z "${ENABLED_PROTOCOLS_FLAGS}" ]; then
  echo "Error: ENABLED_PROTOCOLS_FLAGS is unset"
  echo ${ENABLED_PROTOCOLS_FLAGS}
  exit 1
fi

verify_mplayer_source || exit 1
verify_ffmpeg_source || exit 1

echo "Before prepare_ffmpeg_flags we are standing at..."
pwd
prepare_ffmpeg_flags
verify_ffmpeg_flags || exit 1


# Build FFmpeg (we're now in mplayer-trunk/ffmpeg from the pushd above)
ensure_cd "mplayer-trunk/ffmpeg"
configure_ffmpeg_linux
make -j 16

# Pop back to where we were (should be project root based on build script start)
cd ..
pwd

# Ensure we're in mplayer-trunk directory for mplayer configuration
ensure_cd "mplayer-trunk" || exit 1

echo "FFMpeg compilation finished"
press_any_key

################################################################################
# Configure MPlayer Build for Linux
################################################################################

WARNING_FLAGS='-Wno-unused-function -Wno-switch -Wno-expansion-to-defined -Wno-deprecated-declarations -Wno-shift-negative-value -Wno-pointer-sign -Wno-parentheses -Wdangling-else'

EXTRA_LDFLAGS="-Lffmpeg/libavutil -lavutil -L${OPENSSL_ROOT}/lib -lssl -lcrypto"

EXTRA_CFLAGS="${WARNING_FLAGS} -Os -fPIC -I${OPENSSL_ROOT}/include"

CONFIG_OPTS=''

./configure \
${CONFIG_OPTS} \
--enable-openssl-nondistributable \
--disable-gnutls \
--disable-iconv \
--disable-mencoder \
--disable-vidix \
--disable-vidix-pcidb \
--disable-matrixview \
--disable-xss \
--disable-tga \
--disable-pnm \
--disable-md5sum \
--disable-yuv4mpeg \
--disable-png \
--disable-quartz \
--disable-vcd \
--disable-bluray \
--disable-dvdnav \
--disable-dvdread \
--disable-alsa \
--disable-ossaudio \
--disable-arts \
--disable-esd \
--disable-pulse \
--disable-jack \
--disable-openal \
--disable-nas \
--disable-sgiaudio \
--disable-sunaudio \
--disable-kai \
--disable-dart \
--disable-win32waveout \
--disable-select \
--disable-win32dll \
--disable-gl \
--disable-matrixview \
--disable-vesa \
--disable-sdl \
--disable-aa \
--disable-caca \
--disable-ggi \
--disable-ggiwmh \
--disable-direct3d \
--disable-directx \
--disable-dxr2 \
--disable-dxr3 \
--disable-v4l2 \
--disable-dvb \
--disable-mga \
--disable-xmga \
--disable-xv \
--disable-vda \
--disable-vdpau \
--disable-vm \
--disable-xinerama \
--disable-x11 \
--disable-xshape \
--disable-fbdev \
--disable-mlib \
--disable-3dfx \
--disable-tdfxfb \
--disable-s3fb \
--disable-wii \
--disable-directfb \
--disable-zr \
--disable-bl \
--disable-tdfxvid \
--disable-xvr100 \
--extra-cflags="${EXTRA_CFLAGS}" \
--extra-ldflags="${EXTRA_LDFLAGS}"

press_any_key

# Re-patch FFmpeg before MPlayer build (MPlayer's make will rebuild FFmpeg)
ensure_cd "ffmpeg" || exit 1
patch_ffmpeg_generated_lists
popd  # back to mplayer-trunk

make -j 8

strip_and_upx_final_executable "linux" "${ARCH}"

popd
pwd
set +x
