#!/usr/bin/env bash
################################################################################
# Author: @gubatron
# Modified: 2025 - Refactored for native Linux builds
# This script builds a native fwplayer_linux binary for the host Linux architecture
# functions are defined in build-functions.sh
# ffmpeg codec flag related variables are generated by prepare_ffmpeg_flags.sh
# as output strings which are evaluated by prepare_ffmpeg_flags
################################################################################
#set -x

source build-functions.sh

# Verify we're on Linux
if ! is_linux; then
    echo "Error: Linux builds must be done on Linux"
    exit 1
fi

ARCH=`arch`
if [ ${ARCH} == "i386" ]; then
    ARCH=x86_64
fi

if [ ${ARCH} == "aarch64" ]; then
    ARCH=arm64
fi

echo "Building native Linux player for architecture: ${ARCH}"
press_any_key


cd MPlayer-1.5

make clean
make -C ffmpeg clean

# We now build everything with a single configure from MPlayer and it will sub-sequently build ffmpeg for us
#--enable-static \
./configure \
--disable-gui \
--disable-gnutls \
--disable-librtmp \
--disable-x11 \
--disable-gl \
--disable-esd \
--disable-alsa \
--disable-arts \
--disable-nas \
--disable-jack \
--disable-openal \
--disable-mencoder \
--disable-pulse \
--disable-runtime-cpudetection \
--enable-mad \
--enable-sdl \
--enable-liba52 \
--enable-libvorbis \
--enable-mp3lame \
--disable-live \
--disable-postproc \
--disable-decoder=all \
--enable-decoder=mp3 \
--enable-decoder=ac3 \
--enable-decoder=vorbis \
--extra-cflags="$(sdl-config --cflags) -Wno-error=implicit-function-declaration -Wno-unused-function -Wno-switch -Wno-expansion-to-defined -Wno-deprecated-declarations -Wno-shift-negative-value -Wno-pointer-sign -Wno-parentheses -Wdangling-else -mtune=generic -fPIC -Os" \
--extra-ldflags="-la52 -lvorbis -logg -lmad -lpthread $(sdl-config --libs)"

echo "Done with ./configure, next we build @ $(pwd)"
press_any_key

make -j 16

echo "Done building, now we'll rename mplayer to its new form for FrostWire @ $(pwd)"
strip_and_upx_final_executable "linux" "${ARCH}"
set +x
