#!/usr/bin/env bash
################################################################################
# Author: @gubatron - September 2019
# Modified: 2025 - Refactored for native macOS builds
# This script builds a native fwplayer_osx binary for the host macOS architecture
# functions are defined in build-functions.sh
# ffmpeg codec flag related variables are generated by prepare-ffmpeg-flags.c
# as output strings which are evaluated by prepare_ffmpeg_flags
################################################################################
#set -x

if [ -z "${OPENSSL_ROOT}" ]; then
    set +x
    clear
    echo "OPENSSL_ROOT not set."
    echo
    echo "   It should point to an openssl installation folder (not the sources)"
    echo
    echo "   For macOS native builds:"
    echo "   export OPENSSL_ROOT=${HOME}/src/openssl"
    echo
    exit 1
fi

export PKG_CONFIG_PATH="${OPENSSL_ROOT}/lib/pkgconfig"
source build-functions.sh

# Verify we're on macOS
./is_macos
if [ $? -ne 1 ]; then
    echo "Error: macOS builds must be done on macOS"
    exit 1
fi

ARCH=`arch`
if [ ${ARCH} == "i386" ]; then
    ARCH=x86_64
fi

echo "Building native macOS player for architecture: ${ARCH}"
press_any_key

prepare_enabled_protocol_flags
if [ -z "${ENABLED_PROTOCOLS_FLAGS}" ]; then
  echo "Error: ENABLED_PROTOCOLS_FLAGS is unset"
  echo ${ENABLED_PROTOCOLS_FLAGS}
  exit 1
fi

checkout_mplayer
if [ ! -d "mplayer-trunk" ]; then
  echo "Error: mplayer-trunk not checked out, nothing to build"
  echo ""
  exit 1
fi

# Check out ffmpeg inside mplayer folder
download_ffmpeg
if [ ! -d "mplayer-trunk/ffmpeg" ]; then
  echo "Error: can't find 'ffmpeg' folder inside mplayer-trunk/, can't prepare codec flags without it"
  echo
  exit 1
fi

prepare_ffmpeg_flags
verify_ffmpeg_flags || exit 1

# First we need to build ffmpeg
configure_ffmpeg_macos
make -j 8
popd
echo "FFMpeg compilation finished"
press_any_key

# Paths found in MacOS 10.14.6 - September 2019
MACOS_FRAMEWORKS='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks'
MACOS_USR_INCLUDES='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include'

WARNING_FLAGS='-Wno-unused-function -Wno-switch -Wno-expansion-to-defined -Wno-deprecated-declarations -Wno-shift-negative-value -Wno-pointer-sign -Wno-nullability-completeness -Wno-logical-op-parentheses -Wno-parentheses -Wdangling-else'

EXTRA_LDFLAGS="-framework CoreMedia -framework Security -framework VideoToolbox -liconv -Lffmpeg/libavutil -lavutil -L${OPENSSL_ROOT}/lib -lssl -lcrypto"

EXTRA_CFLAGS="${WARNING_FLAGS} -Os -mmacosx-version-min=10.9 -I${MACOS_FRAMEWORKS} -I${MACOS_USR_INCLUDES} -I${OPENSSL_ROOT}/include"

CONFIG_OPTS=''

################################################################################
# Configure MPlayer Build for macOS
################################################################################
pushd mplayer-trunk

# macOS clang will not do --static for arm64
if [ ${ARCH} == "arm64" ]; then
    CONFIG_OPTS="--cc=${CC}"
    echo "CONFIG_OPTS for arm64: ${CONFIG_OPTS}"
fi

./configure \
${CONFIG_OPTS} \
--enable-openssl-nondistributable \
--disable-gnutls \
--disable-iconv \
--disable-mencoder \
--disable-vidix \
--disable-vidix-pcidb \
--disable-matrixview \
--disable-xss \
--disable-tga \
--disable-pnm \
--disable-md5sum \
--disable-yuv4mpeg \
--disable-png \
--disable-quartz \
--disable-vcd \
--disable-bluray \
--disable-dvdnav \
--disable-dvdread \
--disable-alsa \
--disable-ossaudio \
--disable-arts \
--disable-esd \
--disable-pulse \
--disable-jack \
--disable-openal \
--disable-nas \
--disable-sgiaudio \
--disable-sunaudio \
--disable-kai \
--disable-dart \
--disable-win32waveout \
--disable-select \
--disable-win32dll \
--disable-gl \
--disable-matrixview \
--disable-vesa \
--disable-sdl \
--disable-aa \
--disable-caca \
--disable-ggi \
--disable-ggiwmh \
--disable-direct3d \
--disable-directx \
--disable-dxr2 \
--disable-dxr3 \
--disable-v4l2 \
--disable-dvb \
--disable-mga \
--disable-xmga \
--disable-xv \
--disable-vda \
--disable-vdpau \
--disable-vm \
--disable-xinerama \
--disable-x11 \
--disable-xshape \
--disable-fbdev \
--disable-mlib \
--disable-3dfx \
--disable-tdfxfb \
--disable-s3fb \
--disable-wii \
--disable-directfb \
--disable-zr \
--disable-bl \
--disable-tdfxvid \
--disable-xvr100 \
--extra-cflags="${EXTRA_CFLAGS}" \
--extra-ldflags="${EXTRA_LDFLAGS}"

press_any_key
make -j 8

strip_and_upx_final_executable "macos" "${ARCH}"

popd
pwd
set +x
