#!/usr/bin/env bash
################################################################################
# Author: @gubatron - September 2019
# Modified: 2025 - Refactored for native macOS builds with simplified single-step build
# This script builds a native fwplayer_osx binary for the host macOS architecture
# Audio-only player (no video support)
# We now build everything with a single configure from MPlayer and it will
# subsequently build ffmpeg for us
# functions are defined in build-functions.sh
# ffmpeg codec flag related variables are generated by prepare_ffmpeg_flags.py
# as output strings which are evaluated by prepare_ffmpeg_flags
################################################################################
#set -x

if [ -z "${OPENSSL_ROOT}" ]; then
    set +x
    clear
    echo "OPENSSL_ROOT not set."
    echo
    echo "   It should point to an openssl installation folder (not the sources)"
    echo
    echo "   For macOS native builds:"
    echo "   export OPENSSL_ROOT=${HOME}/src/openssl"
    echo
    exit 1
fi

export PKG_CONFIG_PATH="${OPENSSL_ROOT}/lib/pkgconfig"
source build-functions.sh

# Verify we're on macOS
if ! is_macos; then
    echo "Error: macOS builds must be done on macOS"
    exit 1
fi

ARCH=`arch`
if [ ${ARCH} == "i386" ]; then
    ARCH=x86_64
fi

echo "Building native macOS player for architecture: ${ARCH}"
press_any_key

cd MPlayer-1.5

make clean
make -C ffmpeg clean

# Paths found in MacOS 10.14.6 - September 2019
MACOS_FRAMEWORKS='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks'
MACOS_USR_INCLUDES='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include'

WARNING_FLAGS='-Wno-unused-function -Wno-switch -Wno-expansion-to-defined -Wno-deprecated-declarations -Wno-shift-negative-value -Wno-pointer-sign -Wno-nullability-completeness -Wno-logical-op-parentheses -Wno-parentheses -Wdangling-else'

HOMEBREW_PREFIX=$(brew --prefix)

EXTRA_LDFLAGS="-framework CoreMedia -framework Security -framework VideoToolbox -liconv -L${OPENSSL_ROOT}/lib -lssl -lcrypto -L${HOMEBREW_PREFIX}/opt/mad/lib -lmad -L${HOMEBREW_PREFIX}/opt/a52dec/lib -la52 -L${HOMEBREW_PREFIX}/lib -lvorbis -logg"

EXTRA_CFLAGS="${WARNING_FLAGS} -Os -mmacosx-version-min=10.9 -I${MACOS_FRAMEWORKS} -I${MACOS_USR_INCLUDES} -I${OPENSSL_ROOT}/include -I${HOMEBREW_PREFIX}/opt/mad/include -I${HOMEBREW_PREFIX}/opt/a52dec/include -I${HOMEBREW_PREFIX}/include"

CONFIG_OPTS=''

################################################################################
# Configure MPlayer Build for macOS (with integrated FFmpeg configuration)
################################################################################

# macOS clang will not do --static for arm64
if [ ${ARCH} == "arm64" ]; then
    CONFIG_OPTS="--cc=${CC}"
    echo "CONFIG_OPTS for arm64: ${CONFIG_OPTS}"
fi

# We now build everything with a single configure from MPlayer and it will sub-sequently build ffmpeg for us
./configure \
${CONFIG_OPTS} \
--enable-openssl-nondistributable \
--disable-gnutls \
--disable-iconv \
--disable-mencoder \
--disable-vidix \
--disable-vidix-pcidb \
--disable-matrixview \
--disable-xss \
--disable-tga \
--disable-pnm \
--disable-md5sum \
--disable-yuv4mpeg \
--disable-png \
--disable-quartz \
--disable-vcd \
--disable-bluray \
--disable-dvdnav \
--disable-dvdread \
--disable-alsa \
--disable-ossaudio \
--disable-arts \
--disable-esd \
--disable-pulse \
--disable-jack \
--disable-openal \
--disable-nas \
--disable-sgiaudio \
--disable-sunaudio \
--disable-kai \
--disable-dart \
--disable-win32waveout \
--disable-select \
--disable-win32dll \
--disable-gl \
--disable-matrixview \
--disable-vesa \
--disable-sdl \
--disable-aa \
--disable-caca \
--disable-ggi \
--disable-ggiwmh \
--disable-direct3d \
--disable-directx \
--disable-dxr2 \
--disable-dxr3 \
--disable-v4l2 \
--disable-dvb \
--disable-mga \
--disable-xmga \
--disable-xv \
--disable-vda \
--disable-vdpau \
--disable-vm \
--disable-xinerama \
--disable-x11 \
--disable-xshape \
--disable-fbdev \
--disable-mlib \
--disable-3dfx \
--disable-tdfxfb \
--disable-s3fb \
--disable-wii \
--disable-directfb \
--disable-zr \
--disable-bl \
--disable-tdfxvid \
--disable-xvr100 \
--enable-sdl \
--enable-mad \
--enable-liba52 \
--enable-libvorbis \
--enable-mp3lame \
--disable-decoder=all \
--enable-decoder=mp3 \
--enable-decoder=ac3 \
--enable-decoder=vorbis \
--disable-live \
--disable-postproc \
--extra-cflags="${EXTRA_CFLAGS}" \
--extra-ldflags="${EXTRA_LDFLAGS}"

echo "Done with ./configure, next we build @ $(pwd)"

# ARM64 macOS clang doesn't support -mfpu= flag, remove it from config
if [ ${ARCH} == "arm64" ]; then
    echo "Removing unsupported -mfpu= flag for ARM64 architecture..."
    sed -i '' 's/-mfpu=[^ ]*//g' config.mak
    if [ -f ffmpeg/config.mak ]; then
        sed -i '' 's/-mfpu=[^ ]*//g' ffmpeg/config.mak
    fi
    echo "✓ Cleaned up compiler flags for ARM64"
fi

press_any_key

make -j 8

echo "Done building, now we'll rename mplayer to its new form for FrostWire @ $(pwd)"
strip_and_upx_final_executable "macos" "${ARCH}"
set +x
