#! /bin/bash
./configure --disable-iconv \
    \
    --disable-vidix --disable-vidix-pcidb --disable-matrixview --disable-xss \
    --disable-tga --disable-pnm --disable-md5sum --disable-yuv4mpeg \
    --disable-quartz \
    \
    --disable-vcd --disable-bluray --disable-dvdnav --disable-dvdread \
    \
    --disable-alsa --disable-ossaudio --disable-arts --disable-esd \
    --disable-pulse --disable-jack --disable-openal --disable-nas \
    --disable-sgiaudio --disable-sunaudio --disable-kai --disable-dart \
    --disable-win32waveout --disable-select \
    \

make
cp mplayer ../../frostwire-desktop/lib/native/fwplayer_osx
upx ../../frostwire-desktop/lib/native/fwplayer_osx
