static const FFCodec * const codec_list[] = {
    &ff_aac_decoder,
    &ff_ac3_decoder,
    &ff_alac_decoder,
    &ff_dca_decoder,
    &ff_eac3_decoder,
    &ff_flac_decoder,
    &ff_mp2_decoder,
    &ff_mp3_decoder,
    &ff_opus_decoder,
    &ff_truehd_decoder,
    &ff_tta_decoder,
    &ff_vorbis_decoder,
    &ff_wavpack_decoder,
    &ff_wmav1_decoder,
    &ff_wmav2_decoder,
    &ff_adpcm_g726_decoder,
    NULL };
