static const URLProtocol * const url_protocols[] = {
    &ff_concatf_protocol,
    &ff_fd_protocol,
    &ff_file_protocol,
    &ff_gophers_protocol,
    &ff_hls_protocol,
    &ff_http_protocol,
    &ff_httpproxy_protocol,
    &ff_https_protocol,
    &ff_icecast_protocol,
    &ff_pipe_protocol,
    &ff_rtmp_protocol,
    &ff_rtmps_protocol,
    &ff_tcp_protocol,
    &ff_tls_protocol,
    &ff_unix_protocol,
    &ff_ipfs_gateway_protocol,
    &ff_ipns_gateway_protocol,
    NULL };
