/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2025-10-30-dff1ede4"
#endif /* AVUTIL_FFVERSION_H */
