/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2025-10-29-a9055e46"
#endif /* AVUTIL_FFVERSION_H */
